### ISSUE TITLE
cb-ceiling - too high skill (CSI) score for multiple region plots

### ISSUE THREAD

**Issue by gopa-noaa** [NOAA-GSL/MATS#1044]
Time Series, Valid Time, Threshold, Daily Model Cycle region plots seems to be too high skill values

**Comment by bonnystrong** [comment]
Must be done before implementing  CB-METAR

**Comment by gopa-noaa** [comment]
The region queries where not using subDocType = 'CEILING', hence pulling in more than just the ceiling docs.  The region templates needs to be changed to include subDocType = 'CEILING'.  Time Series Region plots are now looking fine.

**Comment by mollybsmith-noaa** [comment]
Gopa fixed this but didn't close the issue, closing it now.
