### ISSUE TITLE
CB-CEILING app is hanging the server when three webdriver clients run simultaneously and get about three quarters of the way through

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/MATS#1054]
## Describe the bug
If the webdriver tests are set up for three clients (the usual thing) The cb-ceiling tests seem to get about 3/4 finished and they begin to fail, in the end hanging up the server. It doesn't matter what order they are run in. This may have been present for the last couple of releases, possibly due to do changes in the cb-ceiling utility.
## To Reproduce
run the webdriver tests against a local host or mats-dev (a failure will necessitate restarting the server).

## Expected behavior
The tests should complete with no errors
## Additional context
We discovered a dieoff query that was poorly indexed and created a new index for it. It did not solve the problem.

**Comment by gopa-noaa** [comment]
Created branch cb_ceiling_tests_fail_1054 to work on this

**Comment by bonnystrong** [comment]
Needs done before going to production, but not urgent before them.

**Comment by mollybsmith-noaa** [comment]
We definitely fixed part of this by fixing a bug with timeseries averaging.

**Comment by mollybsmith-noaa** [comment]
Actually it looks completely good to go, the averaging bugfix plus some error handling fixed it.
