### ISSUE TITLE
Create some mechanism for couchbase apps to know metadata has changed

### ISSUE THREAD

**Issue by mollybsmith-noaa** [NOAA-GSL/MATS#1081]
In legacy MATS, there's one metadata table per app, so the app monitors that table and updates the selector metadata when the table changes. In couchbase MATS, there's one document per model, so there's not a good way for the app to monitor these besides hardcoding them in. We need a way for the app to know if any of these documents have changed, so it can update the metadata.

**Comment by JeffHamiltonNOAA** [comment]
This will likely be an issue(s) involving more than one developer. We need to have a design meeting with a good chunk of the team to come up with methods for this.

**Comment by ian-noaa** [comment]
Yeah, I can think of at least 3 ways to approach this:

* Couchbase Functions
* The ingest directly informing MATS via REST when metadata has been updated
* Message Queues

**Comment by mollybsmith-noaa** [comment]
I think that a better alternative will be to store all the metadata in one document like we do with mysql, that will be much easier to monitor.

**Comment by mollybsmith-noaa** [comment]
This is no longer an issue with all the models in one document.
