### ISSUE TITLE
Update docker-compose and settings files to use new URL

### ISSUE THREAD

**Issue by mollybsmith-noaa** [NOAA-GSL/MATS#1115]
ITS wants us to fully change from using esrl.noaa.gov/gsd/mats to gsl.noaa.gov/mats. There are a few places in the settings and docker-compose where this needs to be updated. I'll do that when releasing 5.1.3.

**Comment by mollybsmith-noaa** [comment]
This includes checking the picker routes in MatsMethods.

**Comment by ian-noaa** [comment]
@mollybsmith-noaa - I'm finally getting around to this today, apologies for the delay. Which VMs did this need to be done on? Was it just mats-docker? And what did you try before?

I'm anticipating modifying the Docker Compose entries like so:

```diff
upperair:
    # app upperair version is 5.2.0
    image: ghcr.io/noaa-gsl/mats/development/upperair:v5.2.0
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
    environment:
      - DELAY=6
-      - ROOT_URL=https://www.esrl.noaa.gov/gsd/mats/upperair
+      - ROOT_URL=https://gsl.noaa.gov/mats/upperair
      - MONGO_URL=mongodb://matsUser:mu-2019@mongo:27017/upperair?authSource=admin
    volumes:
      - /home/www-data/container_deployment/settings:/usr/app/settings
    depends_on:
      - mongo
    labels:
      - traefik.backend=upperair
-      - traefik.frontend.rule=Host:mats-docker.gsd.esrl.noaa.gov;PathPrefix:/gsd/mats/upperair{id:[0-9]?}
+      - traefik.frontend.rule=Host:mats-docker.gsd.esrl.noaa.gov;PathPrefix:/mats/upperair{id:[0-9]?}
      - traefik.docker.network=web
      - traefik.port=9000
    networks:
      - web
      - backend
```

It was also looking like I'd need to update the traefik.toml and all of the settings.json files.

**Comment by mollybsmith-noaa** [comment]
Also I definitely wouldn’t take the production server down during business hours. We should start with mats-docker-int, our beta server.

**Comment by ian-noaa** [comment]
mats-docker-int has been updated to the new subdomain. The URL is giving a 404 so I've reached out to SSG to double check their NGINX redirects.

**Comment by ian-noaa** [comment]
We've resolved the issues with [gsl.noaa.gov/int-mats.](https://gsl.noaa.gov/int-mats) ITS needed to update their nginx redirects to account for the change from `/gsd/int-mats` to `/int-mats`. We've also added a 302 redirect from the esrl subdomain to the gsl subdomain.

We're planning on doing the same for esrl.noaa.gov/gsd/mats on Wednesday.

**Comment by ian-noaa** [comment]
Dave H & I successfully migrated esrl.noaa.gov/gsd/mats to gsl.noaa.gov/mats this morning. We probably had ~2 minutes of downtime.
