### ISSUE TITLE
better error handling in map plot if table can't be found

### ISSUE THREAD

**Issue by natalieb-noaa** [NOAA-GSL/MATS#1200]
To reproduce:
- go to surface verification
- select plot type map
- select data source "global_nest_phys_dev_d01"
- pick any site(s) & try to plot

This error pops up:

![Image](https://github.com/user-attachments/assets/e2ad0196-253c-487a-a634-5f343ea64247)

**Comment by mollybsmith-noaa** [comment]
The surface app retro vs realtime designation is now handled in metadata, so retros should no longer need to be named with "ret" in this app. They probably still should be for clarity, but the proper database tables will be used regardless.
