### ISSUE TITLE
need to verify at 15-min interval

### ISSUE THREAD

**Issue by mollybsmith-noaa** [NOAA-GSL/MATS#226]
---

Author Name: **bonny.strong** (@bonnystrong)
Original Redmine Issue: 36855, https://vlab.ncep.noaa.gov/redmine/issues/36855
Original Date: 2017-08-08
Original Assignee: jeffrey.a.hamilton

---

Add to MATS only, not legacy.  
Affects processing for loading data.

**Comment by mollybsmith-noaa** [comment]
---

Original Redmine Comment
Author Name: **molly.b.smith** (@mollybsmith-noaa)
Original Date: 2018-01-10T22:46:35Z

---

This is done for ceiling. Next is surface?

**Comment by mollybsmith-noaa** [comment]
---

Original Redmine Comment
Author Name: **dave.turner** (@davidturner53)
Original Date: 2018-01-12T17:09:56Z

---

Yes, I think surface would be the next one to attack.  But we should consider the priority of it, relative to other tasks.  Would it take long to implement in surface?

**Comment by mollybsmith-noaa** [comment]
---

Original Redmine Comment
Author Name: **molly.b.smith** (@mollybsmith-noaa)
Original Date: 2018-01-12T17:50:08Z

---

This shouldn't take too long to implement, although some database work needs to be done. Bonny had the idea of having Bill do it as an introduction to MATS, because Bill asked if he could start helping with MATS development. Randy and I spent part of yesterday trying to get WebStorm set up on Bill's computer, and he has been looking through the surface app code.

**Comment by mollybsmith-noaa** [comment]
---

Original Redmine Comment
Author Name: **molly.b.smith** (@mollybsmith-noaa)
Original Date: 2018-10-15T16:54:39Z

---

Bill has completed the 15 min visibility database, so the only one left to add at this point is 15 min surface. That seems to be lower on the modelers' priorities, so I am decreasing the priority of this issue.

**Comment by mollybsmith-noaa** [comment]
Blocked until we have 15-min surface ingest.

**Comment by bonnystrong** [comment]
What is blocking this?

**Comment by mollybsmith-noaa** [comment]
We actually have a pretty good comment history on this issue. I can't make a 15-min surface app because we have no 15-min surface ingest.

**Comment by mollybsmith-noaa** [comment]
We have successfully completed a 15-minute ceiling and 15-minute visibility app, so I'm closing this issue and creating a separate one for 15-minute surface, which currently has no timeline for completion.
