### ISSUE TITLE
automated testing needs to run on both Mac and Window

### ISSUE THREAD

**Issue by mollybsmith-noaa** [NOAA-GSL/MATS#265]
---

Author Name: **bonny.strong** (@bonnystrong)
Original Redmine Issue: 40141, https://vlab.ncep.noaa.gov/redmine/issues/40141
Original Date: 2017-10-27
Original Assignee: randy.pierce

---

Bug discovered for zooming on Windows that doesn't happen on Macs.  First confirm that automated testing would catch this now if run on Windows.  For future, be sure that all testing is done on both Windows and Macs for every new release.

**Comment by mollybsmith-noaa** [comment]
I honestly think our new testing might work on Windows now, but we need to check.

**Comment by JeffHamiltonNOAA** [comment]
These tasks were reviewed at our 30 minute meeting this morning dedicated
to looking over unassigned tasks on our project board. All of the ones we
closed were either no longer relevant or had been circumvented by another
over time as most were 3+ years old. This was our first meeting with this
purpose, so I'll be sure to add a quick note when I close in the future.

Thanks,

Jeff

-------------------------------------------------------------------------------
Jeff Hamilton
***@***.***
CIRES Research Associate               phone: 303-497-7312
NOAA/OAR/ESRL/GSL/AVID       fax: 303-497-4176
325 Broadway, R/GSL1                    DSRC Room 2B604
Boulder, CO 80305
