### ISSUE TITLE
need an indication of which saved setting was restored to generate a plot.

### ISSUE THREAD

**Issue by mollybsmith-noaa** [NOAA-GSL/MATS#306]
---

Author Name: **randy.pierce** (@randytpierce)
Original Redmine Issue: 47812, https://vlab.ncep.noaa.gov/redmine/issues/47812
Original Date: 2018-03-14

---

When you are looking at a plot that was created from a restored saved setting it would be nice to know which restore setting name was used. This might be an indicator on the restore widget.

**Comment by JeffHamiltonNOAA** [comment]
This issue doesn't seem important and may be redundant, as the user would need to know the name of the settings in order to restore in the first place
