### ISSUE TITLE
add cloudy/clear filter to Surface Map

### ISSUE THREAD

**Issue by mollybsmith-noaa** [NOAA-GSL/MATS#316]
---

Author Name: **jeffrey.a.hamilton** (jeffrey.a.hamilton)
Original Redmine Issue: 47964, https://vlab.ncep.noaa.gov/redmine/issues/47964
Original Date: 2018-03-19
Original Assignee: jeffrey.a.hamilton

---

Per Tanya's suggestion, add the capability to filter based on clear/cloudy conditions at each site in the surface map

**Comment by JeffHamiltonNOAA** [comment]
We need to wait for Couchbase in order to have this capability work efficiently

**Comment by mollybsmith-noaa** [comment]
Our database doesn't support this, we'll do something new in couchbase
