### ISSUE TITLE
Have the date selector clearly indicate whether start or end date is being selected

### ISSUE THREAD

**Issue by mollybsmith-noaa** [NOAA-GSL/MATS#481]
---

Author Name: **molly.b.smith** (@mollybsmith-noaa)
Original Redmine Issue: 66156, https://vlab.ncep.noaa.gov/redmine/issues/66156
Original Date: 2019-07-17
Original Assignee: molly.b.smith

---

The selector should say something like "Choosing start date" or "Choosing end date" for those respective actions.

**Comment by bonnystrong** [comment]
Not sure why this was closed.  Not a high priority, but work has not been completed.

**Comment by mollybsmith-noaa** [comment]
The new date widget does this automatically be highlighting the prospective date range as a user is mousing over numbers.
