### ISSUE TITLE
we really need to implement logging support for all the apps.

### ISSUE THREAD

**Issue by mollybsmith-noaa** [NOAA-GSL/MATS#55]
---

Author Name: **randy.pierce** (@randytpierce)
Original Redmine Issue: 21349, https://vlab.ncep.noaa.gov/redmine/issues/21349
Original Date: 2016-08-18
Original Assignee: randy.pierce

---

Ideally all the apps would log to a server instance in the dmz so that the logs can be accessed from anywhere.
Also the logs need to be managed, purged etc.
There needs to be a decent client app for reading and analyzing the logs.
Notification would be nice.

**Comment by randytpierce** [comment]
prometheus and docker have superseded this issue.
