### ISSUE TITLE
clean up MATS build script a little to make it more compatible with METexpress and submodules.

### ISSUE THREAD

**Issue by mollybsmith-noaa** [NOAA-GSL/MATS#574]
---

Author Name: **randy.pierce** (@randytpierce)
Original Redmine Issue: 83290, https://vlab.ncep.noaa.gov/redmine/issues/83290
Original Date: 2020-09-28
Original Assignee: randy.pierce

---

relatively minor cleanup

**Comment by randytpierce** [comment]
This is working now. Molly and I reviewed it yesterday.
