### ISSUE TITLE
cbUtilities, couchbase ingest, app conversion architecture and design review

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/MATS#599]
We need to have architecture and design review of milestone 1 couchbase ingest, milestone 1 cbUtilities, and app conversion.

**Comment by randytpierce** [comment]
Jeff and I have done quite a bit of this, and Molly and Ian have participated but I think there are still a couple of significant changes to review.

**Comment by bonnystrong** [comment]
Randy, what's the status of this?  I thought Milestone 1 was complete, yet we have this issue in the Backlog for it?

**Comment by bonnystrong** [comment]
Still need to know why we have a Milestone 1 issue in the Backlog.  It can no longer be related to Milestone 1 since we've moved on from there.  Does it need to be completed for Milestone 2?

**Comment by bonnystrong** [comment]
Need to get this updated for milestone and repo

**Comment by bonnystrong** [comment]
No longer relevant

**Comment by randytpierce** [comment]
Closing this issue. We had intended a formal review but the review was accomplished with several smaller meetings.
