### ISSUE TITLE
Implement sites matching code in cb-ceiling dataseries

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/MATS#601]
This is the sites match part of the time series. It requires a better query . Refer to this couchbase forum issue
https://forums.couchbase.com/t/n1ql-combine-objects-in-an-array-based-on-specific-field-values-being-equal/30358/2

**Comment by mollybsmith-noaa** [comment]
Rather than try to replicate the in-query matching for sites plots in couchbase, we should move matching out of the query entirely. I should have time to do that next month.

**Comment by mollybsmith-noaa** [comment]
I have moved matching out of the queries for all plot types except contourDiff. I'll probably end up doing that one too for consistency's sake, but it generates a staggering number of sub-values, so I'm not convinced that it's faster, unlike the rest of the plot types which are substantially faster this way. Once that is done, we can finally implement our full range of data queries in couchbase!

**Comment by mollybsmith-noaa** [comment]
I was gone most of this week, but I'm happy to report that the matching contour difs are fully working, and I've verified that all the plot types and diff curves are producing the correct values, so once the error bar issue is complete, all that remains is to fix the text output to show hits, misses, etc, make sure that the code is well commented, and propagate it to the rest of the apps.

**Comment by mollybsmith-noaa** [comment]
The sites matching has now been fully externalized from the query in all ctc plot types. At some point we should do this for the partial sums apps too. Probably when we're ready to build a couchbase prototype of those apps.
