### ISSUE TITLE
Vscode development environment

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/MATS#610]
JetBrains does not have SAM ( "System for Award Management" ) registration so we cannot renew our licenses. We have decided to try to get VScode working as an alternative development environment. Put any notes here.

**Comment by randytpierce** [comment]
It seems that if we are going to use vscode we should put an entry
.vscode/
into the top level .gitignore.
I loaded all of Ians extensions and a couple of others that I thought looked interesting and had over a million upvotes...
gitgraph
meter extension pack - a collection of popular meteor extensions
MeteorHelper - command line meteor

These are my extensions....
gsd-sslvpn-179:VXingest randy.pierce$  code --list-extensions
alefragnani.project-manager
alexkrechik.cucumberautocomplete
DavidAnson.vscode-markdownlint
dbaeumer.vscode-eslint
eamodio.gitlens
esbenp.prettier-vscode
hashicorp.terraform
HookyQR.beautify
mhutchie.git-graph
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-vsliveshare.vsliveshare
msjsdiag.debugger-for-chrome
naumovs.color-highlight
ramonitor.meteorhelper
timonwong.shellcheck
walkme.Meteor-extension-pack
yzhang.markdown-all-in-one

Perhaps we should all enable code from the PATH and list extensions so we can see which ones we are using?
https://code.visualstudio.com/docs/setup/mac. - launching from the command line.

For the moment I am using the Webstorm/Pycharm directories with the .idea and .vscode folders both ignored so that both vscode and jetbrains ide's still work. At least until I am comfortable with debugging in vscode.

**Comment by randytpierce** [comment]
When in doubt hit escape.

**Comment by randytpierce** [comment]
This launch.json seems to work for the VXingest program. I did have to trim leading whitespace from one of the program args, and I did have to specify the proper python3. cmd shift P and use "select interpreter"

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [  
        {
            "name": "Run gsd ingest metars V01",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/classic_sql_to_cb/run_sql_ingest_threads.py",
            "args": ["-s ${workspaceFolder}/test/load_spec_gsd-hrrr-v01.yaml", "-c ${HOME}/adb-credentials-local", "-f 1614011400", "-l 1614015000"],
            "console": "integratedTerminal",
            "cwd": "${workspaceFolder}/classic_sql_to_cb",
            "env": {
                "PYTHONPATH":"${cwd}"
            }
        }
    ]
}

**Comment by randytpierce** [comment]
So I have one possible configuration for debugging meteor apps in Vscode working. I think I can make it more strait-forward but this does work.
Steps.
Step 1) create a launch.json that looks like this. NOTE: we may need a configuration for each app that we want to debug, or we will have to change the launch.json to refer to an app the we want to run. 
Step 2) set a breakpoint if you want to debug the startup stuff
Step 3) run the following command (modified for the specific app) in the terminal
meteor --settings ${HOME}/mats-settings/configurations/dev/settings/cb-ceiling/settings.json --inspect-brk
Step 4) run the debugger so that it attaches to the session, it will hit any breakpoints.

To stop just ^C in the terminal and stop the debug session with the little stop icon or from the run pull down.

Restarting the app causes the debug session to restart so you can make changes and refresh (restart) and keep debugging. It seems to work ok.

There should be a way to put the script command into the package.json for each app and have the run command be generic but I don't have that quite worked out yet. This will get us started.

**Comment by randytpierce** [comment]
There was a mistake in the python launch.json. ${HOME} is NOT valid in a launch config. It should be  ${env:HOME}
like this...

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [  
        {
            "name": "Run gsd ingest metars V01",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/classic_sql_to_cb/run_sql_ingest_threads.py",
            "args": ["-s ${workspaceFolder}/test/load_spec_gsd-hrrr-v01.yaml", "-c ${env:HOME}/adb-credentials-local", "-f 1614011400", "-l 1614015000"],
            "console": "integratedTerminal",
            "cwd": "${workspaceFolder}/classic_sql_to_cb",
            "env": {
                "PYTHONPATH":"${cwd}"
            }
        }
    ]
}

**Comment by randytpierce** [comment]
I also added the extension "github pull requests and issues" because of this web page.
https://code.visualstudio.com/docs/editor/github
I think this is what is giving me a bunch of extra git stuff on the left side bar.
In addition to sources and commits I have file history, branches, remotes, stashes, and tags.

**Comment by randytpierce** [comment]
I am documenting this in the team drive and referencing this issue.

**Comment by randytpierce** [comment]
These are test extensions for vscode...
Python Test Explorer for Visual Studio Code
Test Adapter Converter
Test Explorer UI
Test Explorer Live Share

**Comment by mollybsmith-noaa** [comment]
I'm actively working on implementing all of this this week.

**Comment by mollybsmith-noaa** [comment]
After much failure to get VSCode to actually run apps directly, I've added the following lines have been added to my .bash_profile:

```
# Meteor run commands

alias runapp='meteor run --settings settings/settings.json'
alias debugapp='meteor run --inspect-brk --settings settings/settings.json'

```
I can execute them in any app directory to run meteor.

Then I view the debugger output in VSCode using a modified version of Randy’s “attach” configuration, which _is not the same as actually running it there, VSCode_:

    ```
"version": "0.2.0",
    "configurations": [
      {
        "type": "pwa-node",
        "name": "aircraft",
        "request": "attach",
        "cwd": "${workspaceFolder}/apps/aircraft", 
        "skipFiles": [
          "<node_internals>/**/*.js",
          "${cwd}/node_modules/**/*.js",
          "${cwd}/.meteor/**/*.js",
          "/${HOME}/.meteor/packages/*/.*/**/*.js"
        ],
        "port": 9229,
        "outputCapture": "std",
        "restart": true
      }
    ]
```

This does at least, work. I'm therefore closing this issue and moving on to actual app development.
