### ISSUE TITLE
rework home app and redirected settings page to accommodate curve params in settings.json files.

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/MATS#622]
Since we added curve params to the settings the home app has been broken, along with the redirected settings page. This has to be fixed before we can automatically deploy on rancher again.

**Comment by randytpierce** [comment]
created issue branch issue-622 to do this rework.

**Comment by randytpierce** [comment]
I decided to update the helm charts first because it makes testing this work much easier

**Comment by bonnystrong** [comment]
Does this support the scorecard?  Or should it go back in Backlog

**Comment by mollybsmith-noaa** [comment]
This work is no longer necessary because the curveParams once again live in the MATS/METexpress code and not the settings.
