### ISSUE TITLE
get new apps (based on Ians container work) running in rancher

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/MATS#647]
In order to get these apps ready for running in a kubernetes environment we should get them running in our rancher environment. That is the easiest way to proceed. This effort is dovetailing with some of the changes that need to be made to be compliant to our security checking such as using a non-privileged user which requires using non-privileged ports on the backend network within the stack.

This effort will block the HELM chart upgrades.

**Comment by ian-noaa** [comment]
Closing in favor of #764.
