### ISSUE TITLE
Switch internal dev environment to ghcr images

### ISSUE THREAD

**Issue by ian-noaa** [NOAA-GSL/MATS#655]
Update our internal dev deployment to use the new images from ghcr.io.

* We may need to provide a login token as the images are private
* Will we want to do this to mats int as well?

**Comment by mollybsmith-noaa** [comment]
In answer to the first question, I’d like to get the error bar / site
matching release out by itself, but we can switch over the images after
that. In answer to the second, yes, I manually edit the docker-compose.yml
files. :%s/4.1.2/4.2.0/g in vi.

**Comment by ian-noaa** [comment]
This is done for our preint environment and tests are passing both there and in the dev environment. We could roll this out to other environments as well. However, I think we ultimately want to target Kubernetes as the deployment platform so defer further work on this in favor of #647.
