### ISSUE TITLE
Externalize stat calculations in partial sums apps

### ISSUE THREAD

**Issue by mollybsmith-noaa** [NOAA-GSL/MATS#663]
Before we create a couchbase partial sums app, we will have to externalize the statistical calculations the way we have done for the contingency table apps. We should do this anyway because it's honestly better practice.

**Comment by bonnystrong** [comment]
What's the status on this?

**Comment by mollybsmith-noaa** [comment]
I’ve started work but haven’t reached any concrete milestones yet, so I
didn’t have anything to put in an update other than moving the issue to “in
progress”.

**Comment by mollybsmith-noaa** [comment]
Good progress on this issue this week! Nearly all of the common code changes are done, and the landuse app is using the new data methods. I just need to propagate them into surface and upperair (and surfrad? I need to have a closer look at that one, its database is really different).

**Comment by mollybsmith-noaa** [comment]
This is done and working well, and matches all of the old data routines with manual testing.
