### ISSUE TITLE
Add ability to control which apps are released

### ISSUE THREAD

**Issue by ian-noaa** [NOAA-GSL/MATS#684]
Work has picked up on cb-ceiling. We should add it to CI. 

Questions:

* Does it need to be excluded from any deployments?

**Comment by mollybsmith-noaa** [comment]
As of now we only want to build/deploy this app from the development branch (or feature branches), even though the code does exist on main.

**Comment by ian-noaa** [comment]
Sounds good. Thanks, @mollybsmith-noaa! How long will we want to keep cb-ceiling out of the production image repository?

It seems like this is a thing we'll want to be able to do regularly so I'm thinking I should probably pull the deploy step into its own job so we can control what gets pushed to the image registries.

**Comment by mollybsmith-noaa** [comment]
I think we just want to keep it off production until it can be okayed by a beta tester, which it won’t be as it is now. Shouldn’t be too long the way things are going, though.

And sounds good about the rest!
