### ISSUE TITLE
Add RRFS 3km NA to MATS precipitation apps

### ISSUE THREAD

**Issue by davidturner53** [NOAA-GSL/MATS#695]
Improving precipitation biases is an important priority for RRFS research.  We need to get the RRFS 3km model (the GSL experimental) into our precipitation apps (esp 24-h precipitation and ideally the 1-h precipitation).  Adding to gauge precipitation app is nice but not critical at the moment.

**Comment by mollybsmith-noaa** [comment]
Can you move this to the VxIngestLegacy repo and assign it to Jeff? It’s
not really MATS development.

**Comment by JeffHamiltonNOAA** [comment]
Hi Dave, Molly,

I'll move it over and close this one.

Jeff

-------------------------------------------------------------------------------
Jeff Hamilton
***@***.***
CIRES Research Associate               phone: 303-497-7312
NOAA/OAR/ESRL/GSL/AVID       fax: 303-497-4176
325 Broadway, R/GSL1                    DSRC Room 2B604
Boulder, CO 80305
