### ISSUE TITLE
investigate archiving old projects in VLab redmine

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/MATS#731]
I believe MATS is the only repo that we had in VLAB so this issue is here. We want to investigate if there is a way to archive the old redmine stuff.

**Comment by randytpierce** [comment]
According to this... https://www.redmine.org/projects/redmine/wiki/redmineprojects#:~:text=From%20the%20projects%20list%2C%20click,any%20subproject%20is%20also%20archived.

it is possible to archive a redmine project. I have sent a not to Tom Filliaggi for comment with regards to VLAB. I'll note his response here when I get it.

**Comment by bonnystrong** [comment]
Review.  Randy thinks this is not needed based on discussions with Tom Filliagi.
