### ISSUE TITLE
Missing data from AMDAR app

### ISSUE THREAD

**Issue by davidturner53** [NOAA-GSL/MATS#752]
The last valid data in the AMDAR / upper Air app for the HRRR_ops_iso seems to be 6/16/2022.  Need to investigate why the more recent few months of data are not in the DB.

**Comment by mollybsmith-noaa** [comment]
This is because the ingest is looking for data in /lfs1/BMC/public/data/grids/hrrr/conus/wrfprs/grib2/, which is largely empty, instead of /public/data/grids/hrrr/conus/wrfprs/grib2/, which is full of current data. I will fix the path and ask Jeff if there's any mechanism for backfilling AMDAR data.

**Comment by mollybsmith-noaa** [comment]
A few other models also have this problem:

- RAP_OPS_iso_130
- NAM
- GFS

I've corrected the path for all of them.

**Comment by mollybsmith-noaa** [comment]
The realtime seems to work again, but I have no idea if there's a way to backfill AMDAR data, and will ask Jeff about it when he returns.

**Comment by JeffHamiltonNOAA** [comment]
This can be done, but no workflow exists to make it happen. However, it should be fairly easy to take my backfilling scripts that handle UA, surface, ceiling, and visibility and add an aircraft component to it.

**Comment by mollybsmith-noaa** [comment]
BTW, this is actually a two-year gap, not two months. The ingest stopped in June of 2020, not 2022.

**Comment by mollybsmith-noaa** [comment]
If we backfill this, we'll do it in conjunction with Jason's PBL calculation code. When that issue is created, I'll add its number here.
