### ISSUE TITLE
Couchbase map plot queries not aggregating properly

### ISSUE THREAD

**Issue by mollybsmith-noaa** [NOAA-GSL/MATS#756]
The map plot couchbase queries are still not aggregating by station. This will probably take another meeting between Randy and me to clear up.

**Comment by bonnystrong** [comment]
Molly says need to deal with this within the next month.  One part of Couchbase version that is not working.  Has to be done before app is fully tested.

**Comment by mollybsmith-noaa** [comment]
This is blocked until we have actual CTC documents again. They are currently in the process of being regenerated.

**Comment by bonnystrong** [comment]
Now have CTC docs and ready to proceed.

**Comment by mollybsmith-noaa** [comment]
Jeff figured out the magic syntax to make this work last week, so this issue is resolved.
