### ISSUE TITLE
Update mongo version in MATS/METexpress containers

### ISSUE THREAD

**Issue by mollybsmith-noaa** [NOAA-GSL/MATS#760]
Our MATS/METexpress docker containers are currently using mongo 4.2, which is considered legacy for meteor 2.7.3, our current meteor version. We should update the container mongo to be more compatible with meteor.

**Comment by mollybsmith-noaa** [comment]
I've updated the mongo versions on mats-docker-dev and mats-docker-preint and everything seems to be working well. I'll do mats-docker-int and mats-docker concurrently with our next release.

**Comment by bonnystrong** [comment]
Latest mongo has some hardware requirements, that showed up on model-vxtest.

**Comment by mollybsmith-noaa** [comment]
mongo has been updated on our docker VMs.
