### ISSUE TITLE
Create more server-side routes in MATS

### ISSUE THREAD

**Issue by mollybsmith-noaa** [NOAA-GSL/MATS#762]
I've added server-side routes in MATS to retrieve the statistics and variables in each app, but we really need more routes, to get the options/optionMaps available for all the selectors.

**Comment by mollybsmith-noaa** [comment]
I've created a nice API to get the optionMaps for all selectors relevant to the scorecards, and it works really well! I need to add a few more routes to retrieve valueMaps from selectors which have them, but then I'll be able to do the front end for the scorecard app.

**Comment by mollybsmith-noaa** [comment]
Current API documentation is at https://docs.google.com/document/d/1nX_hB0P9VyUokSYxWwtHwmB6MrTtklX0ZFlgOUtkyEg/edit?usp=sharing

I will move it to the team drive when it has the valueMap routes in it.

**Comment by bonnystrong** [comment]
Essential for scorecard.

**Comment by mollybsmith-noaa** [comment]
I have added all of the necessary valuesMap routes, and updated the API documentation at https://docs.google.com/document/d/1nX_hB0P9VyUokSYxWwtHwmB6MrTtklX0ZFlgOUtkyEg/edit?usp=sharing (with some instructions on how to use the routes). I'll submit a pull request to get the API onto development.
