### ISSUE TITLE
Inconsistent statistical results using partial sums vs select station aggregations

### ISSUE THREAD

**Issue by JeffHamiltonNOAA** [NOAA-GSL/MATS#768]
When creating Upper Air RAOB plots using the predefined HRRR domain compared to select stations that roughly equal the HRRR domain, wildly different results are present in the HRRR OPS, especially in wind statistics.

A good example of this put together by Amanda Back is in this presentation:

[raob_wind_rmse_issues_2.pptx](https://github.com/NOAA-GSL/MATS/files/9568096/raob_wind_rmse_issues_2.pptx)

We expect some differences, but they should be minimal and not statistically significant

**Comment by mollybsmith-noaa** [comment]
Jeff found a unit error for wind direction in MATS. I corrected it, but the results between the two region types are still dissimilar.

**Comment by bonnystrong** [comment]
Dave puts this at the highest of the high priority issues

**Comment by JeffHamiltonNOAA** [comment]
I've completed an analysis of the queries in both sections of the UA app. The algorithms that calculate the statistics were the same, except for a small error in squared sums for wind verification that was missed during the unit conversion error patch, but the main difference lies in the vertical interpolation/resolution of the soundings produced. I've created a document with details, and we will discuss more at the team and ingest meetings:

https://docs.google.com/document/d/1JggzQG5Gb1AvuEVbrazW8d5wuJaowLeodRUDiaBCabo/edit?usp=sharing

**Comment by mollybsmith-noaa** [comment]
I implemented Jeff's changes in MATS and the curves now produce very similar results. This bug is fixed.
