### ISSUE TITLE
implement authentication either for MATS in general, or for the scorecard

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/MATS#789]
Scorecards will need some sort of authentication in order to organize the status page.

**Comment by randytpierce** [comment]
Please refer to the discussion  https://github.com/NOAA-GSL/MATS/discussions/795
At the moment I am thinking NOAA SSO is the way to go.

**Comment by bonnystrong** [comment]
Molly notes that FAA people use MATS currently.

**Comment by randytpierce** [comment]
I have implemented Meteor authentication.password for the time being. This allows users to create an account with their email address and set a simple password. The code can find users and find which user is logged in, which is sufficient for the scorecard purposes for now.

**Comment by randytpierce** [comment]
Closing this. Enhancing the authentication mechanism to support roles will be another issue.
