### ISSUE TITLE
Update the Babel Runtime so it's consistent across the MATS apps

### ISSUE THREAD

**Issue by ian-noaa** [NOAA-GSL/MATS#791]
## Problem
During work on https://github.com/NOAA-GSL/MATS/pull/778#discussion_r976632139, it was discovered that the Babel runtime version was inconsistent across the MATS apps.

## Solution
Update babel runtime to a consistent version across all MATS apps.

## No Go's
N/A

## Tasks
N/A

**Comment by mollybsmith-noaa** [comment]
I have updated both @babel/runtime (to v7.19.0) and other meteor and npm packages across MATS and METexpress.
