### ISSUE TITLE
implement a scorecard repeat selector i.e. a schedule widget 

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/MATS#800]
Please refer to disccussion #801
The scheduler needs to be able to schedule "once and done" jobs that execute at a given time, as well as jobs that execute at a given time and then repeat on a set interval.  The "once and done" jobs are configured with a MATS date ranges selector.

The jobs that repeat on a schedule must be configured with relative date ranges, i.e. a date range so many hours/days/weeks prior to the schedule time.

This makes it logical that there should be a radio type selector that chooses between custom and relative. When custom is chosen a normal MATS dates selector widget is visible, but when relative is chosen a relative time selector is visible, perhaps a choice of hours/days/weeks and a number entry.

There must also be a scheduling widget and associated back end. I am thinking "bree js"  https://github.com/breejs/bree might be a good choice for the scheduler. There are others but bree has the ability to synchronize over multiple instances. Since it is inevitable that we will have multiple scorecard instances running simultaneously this becomes important.

**Comment by JeffHamiltonNOAA** [comment]
This is working. Closing for Randy
