### ISSUE TITLE
create a statistical significance parameter for parameter group

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/MATS#804]
See discussion #803.
Here are a few notes from that discussion. I'm not 100% sure (with a statistical significance of +- 5%) that we fully understand this yet, but we should take what we have and add it to the prototype so that we can get more feedback from the modelers.

For statistical significance an initial approach should be a plot param that is labeled 'statistical significance threshold' which applies the percentile values at which the symbols change. It needs to identify the symbol colors and the percentiles. It applies to the entire scorecard. The default values are 95% and 99% and there should be an option for std deviation (ex. 1sd, 2sd, 3sd)

percentile o std dev o
percentile
[99%] [color]
insignificant [color]
std dev
1sd
2sd
3sd

**Comment by bonnystrong** [comment]
Randy, I'm assuming this is for the Scorecard, but nothing in the issue indicates this.  Could you put something in the title that shows if an issue is related to the scorecard?

**Comment by randytpierce** [comment]
This has been implemented and is part of the pull request for scorecard1 to development.
