### ISSUE TITLE
Figure out appropriate lint and formatting extension settings for the team so that we have consistency.

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/MATS#814]
I propose that we use ESlint on vscode and figure out its configuration for all of MATS, then format the whole thing so the code is consistently formatted.

**Comment by bonnystrong** [comment]
Molly: don't like how it splits up lines, but if Randy likes it she'll get used to it.

**Comment by bonnystrong** [comment]
Good enough - close it.
