### ISSUE TITLE
Upgrade cb_ceiling queries for new CB data model

### ISSUE THREAD

**Issue by gopa-noaa** [NOAA-GSL/MATS#858]
CB data model was changed for performance reasons, and new queries needs to replace existing old data model queries in the cb_cieling app.

**Comment by gopa-noaa** [comment]
All apps are now upgraded to new queries, and use SQL templates to reduce code clutter.  Need to test contour_diff plots and verify plot points with CB data.

**Comment by gopa-noaa** [comment]
contour_diff plots are working now. Pending actions before merge to development 1) code review 2) cross-check plot data points with data in Couchbase.

**Comment by gopa-noaa** [comment]
All plot types changed to => private soft linked and read as assets/app/sqlTemplates

**Comment by mollybsmith-noaa** [comment]
Maybe grab the query from the MySQL version, see what fields are expected to return, and make sure you have all of those fields?

**Comment by gopa-noaa** [comment]
I am done with all tasks on this PR.  After check-in I am getting a PR failed email, not sure why, this is what it says:
![Screen Shot 2023-04-05 at 3 34 42 PM](https://user-images.githubusercontent.com/114701068/230131564-07295d12-1966-4a1a-9870-71a957e37a27.png)

**Comment by bonnystrong** [comment]
Should have been closed a couple weeks ago.
