### ISSUE TITLE
It appears that the metadata refresh is happening more than once - many times

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/MATS#874]
## To Reproduce
You have to instrument the startup of an app with log statements
## Expected behavior
it should only happen once

**Comment by randytpierce** [comment]
I am reducing this in priority. It isn't happening more than once for a single refresh of the app. It's just happening omn each refresh. It should only really need to do this if the metadata has changed or if there isn't any data in the mongo collection. We can think about how to optimize this later.

**Comment by bonnystrong** [comment]
Will likely be a problem when we do public scorecard.

**Comment by mollybsmith-noaa** [comment]
I think I fixed this with some asyncs
