### ISSUE TITLE
Implement the creating of a settings (app plotParams, I believe) object from a scorecard plotParams.

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/MATS#878]
save and restore settings actions from the ui are implemented in .../MATScommon/meteor_packages/mats-common/templates/plot/plot_list.js.  Look around line 175 in the big switch statement.

We need a mechanism that the scorecard uses to derive and save a settings object for a particular application that instead of being derived from a plotparams object, instead creates an appropriate plotparams object - derived from the scorecard plotparams - for the underlying time series plot for the specific application for a range of cells.this plotparam object might be for only a single cell of the scorecard - like the first one, and then we will modify the other values in the plotparams depending on which cell is clicked. The modifiable values - for example the region, variable, statistic, and forecast length will  probably have to be added to the scTableSigTd helper in the scorecardDisplay.js scTableSigTd event handler (which currently points to the application page). That application link will need to change to be something like .... 
e.view.window.open("https://www.esrl.noaa.gov/gsd/mats/" + application + "/" + region + "/" + variable + "/" + statistic + "/" + fcst_len, "_blank"); .... and then this link must be represented by a new Flowrouter route in MATScommon/meteor_packages/mats-common/imports/startup/client/routes.js. Some of this work is to be completed under issue #879 and #880

**Comment by mollybsmith-noaa** [comment]
The design plan is at https://github.com/NOAA-GSL/MATS/discussions/892

**Comment by mollybsmith-noaa** [comment]
Clicking on a scorecard cell now produces an object with all the necessary information for a timeseries plot.
