### ISSUE TITLE
Implement the API for saving the settings to a server. (I sure would like to have these shared between instances somehow - store them in couchbase?) Make the scorecardDisplay do this.

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/MATS#879]
Refer to issue #878 which is about creating a saved settings that can be used as a template to restore a time series plot to a mats application by replacing certain specific values with parameters to a Flow Route. The modifiable values - for example the region, variable, statistic, and forecast length will  probably have to be added to the scTableSigTd helper in the scorecardDisplay.js scTableSigTd event handler (which currently points to the application page). From issue # 878 ... That application link will need to change to be something like .... 
e.view.window.open("https://www.esrl.noaa.gov/gsd/mats/" + application + "/" + region + "/" + variable + "/" + statistic + "/" + fcst_len, "_blank"); .... and then this link must be represented by a new Flowrouter route in MATScommon/meteor_packages/mats-common/imports/startup/client/routes.js.  This is the issue for creating that FlowRouter route.

There are questions.... 
1) should these saved settings be visible to the users and able to be restored as time series plots? If so how do we name them? If not then how do we hide them.
2) Should they perhaps be saved in a different collection?
3) Should they be saved in Couchbase? That would make them available to multiple servers. That way they could be moved into and out of the matsCollections.CurveSettings or just restored from Couchbase bypassing matsCollections.CurveSettings altogether (I like this better personally). 
4) The current save and restore mechanisms are managed in MATScommon/meteor_packages/mats-common/imports/startup/api/matsMethods.js.saveSettings and then restored in plot_list.js by just retrieving them out of the matsCollections.CurveSettings collection directly by the client. We would need to implement a new matsMethods.restoreSettingsFromCouchbase and  matsMethods.saveSettingsToCouchbase method and decide how the settings fit into the Couchbase data model.

**Comment by mollybsmith-noaa** [comment]
As far as scorecard-defined windows go, this will be done with a temporary mongo collection, as described in https://github.com/NOAA-GSL/MATS/discussions/892

**Comment by mollybsmith-noaa** [comment]
I'm re-assigning this to Gopa, because he will do the work of storing the scorecard settings in couchbase for the destination apps to retieve.

**Comment by mollybsmith-noaa** [comment]
(As described in #892, we can't use mongo because each app technically has its own mongo instance, so couchbase it is!)

**Comment by bonnystrong** [comment]
This has been completed by Molly and Gopa.
