### ISSUE TITLE
cb_ceiling app, time-series plot, excessive execution time with all stations selected

### ISSUE THREAD

**Issue by gopa-noaa** [NOAA-GSL/MATS#894]
Time Series query, if you select all stations for a month, the query never comes back, or at least did not come back in a few hours.
Problem could be there for other queries too, haven't yet tested them.

**Comment by gopa-noaa** [comment]
Just jotting down some points here to help jog the gray cells ...

Making use of the Couchbase evaluation & test framework I am setting up in:
VxIngest/test/cb_evaluation_tests

I am checking in things under branch "couchbase-evaluation-tests" in the VxIngest repo.
You can find the query SQLs I am using in: 

VxIngest/test/cb_evaluation_tests/cb_jest_tests/SQLs/experimental/

I am trying to narrow down where the execution time is being used up.  I also need to cross check this with CouchBase's query profiling too.

Anyway with everything from the time series station query stripped down, just fetching stations, here are the results (please note that Couchbase does come back, and not just go to lunch fore ever!)

 PASS  __tests__/experimental/experimental_0.js (314.423 s)
  Experimental Couchbase tests
    ✓ Establish CouchBase connection (1 ms)
    ✓ Test: Get data for 3 named stations (5090 ms)
    ✓ Test: Get data for N named stations (7220 ms)
    ✓ Test: Get data for all named stations (301375 ms)
Non-linear, since N above is about 60, so we go from: 1500 ms for 3 => 120 ms (for 60) => 50 ms (for 6000)
This is kind of encouraging, I think, and possibly opens up some avenues we can explore.

**Comment by gopa-noaa** [comment]
I have a basic code version (call it middle-layer instead of middle-ware) of the time series stations query.  All stations for 1 month performance looks promising.  I am seeing minor differences in the stats JSON between the middle-layer version and the SQL version. Will work with @mollybsmith-noaa or @JeffHamiltonNOAA to figure out why we are seeing some differences.  If the middle-layer version works, the middle-layer could (for now) reside on MATS app server side code.

**Comment by gopa-noaa** [comment]
Highly async middle-tier code, we now have the all stations time down to 28 seconds.  With the 3 stations same that for our original query, the stats generated looks identical.  I will try to add the code temporarily to cb_ceiling to test all stations time series plot, so still keeping my fingers crossed.

**Comment by gopa-noaa** [comment]
After code review with @mollybsmith-noaa  , we will keep the SQL templates with the app, and middle-tier code will move to MATSCommon.

**Comment by gopa-noaa** [comment]
Needs review, values seem low, needs to cross check with CouchBase

**Comment by mollybsmith-noaa** [comment]
Gopa finished this but forgot to close the issue, closing it now.
