### ISSUE TITLE
The scorecard backend data does not seem to be reactive

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/MATS#902]
## Describe the bug
The scorecard backend data does not seem to be reactive. The mechanism is in processScorecard.js and it is supposed to take a given scorecard and load it into a mongo collection. That mongo collection should be reactive with respect to the scorecardDisplay. As the vxDataProcessor updates the scorecard in the database there will be a server side route that updates the mongo collection. This should cause the view to update. That last part is not working properly. 

## To Reproduce
1. use the scorecard app to create a scorecard
2. display that scorecard
3. use a mongo client to modify one of the result cells in the mongo scorecard entry
4. See that the display does not automatically update in response to the data change.

## Expected behavior
The scorecardDisplay should dynamically update to reflect the data change in the Mongo Scorecard document.

**Comment by mollybsmith-noaa** [comment]
This works now. Meteor mongo is a bit different from standalone mongo, so I had to use:
```
      const cursor = matsCollections.Scorecard.find({"_id": scorecard.docID});
      const handle = cursor.observeChanges({
        changed(id, fields) {
          refreshScorecard(userName, name, submitted, processedAt)
        }
      });
```
