### ISSUE TITLE
Add a version field to the scorecard document

### ISSUE THREAD

**Issue by ian-noaa** [NOAA-GSL/MATS#935]
## Problem

The data processor assumes certain that scorecard documents will have a certain structure. If that structure changes, processing those documents can fail.

As an example - we would like to move the `blockApplication` field that stores the MATS URL from the individual blocks to the root level of the scorecard document since it applies to the document as a whole instead of the individual blocks.

## Solution

Add a `version` field to our scorecard document so that we can determine which document layout we're dealing with and so we can easily support mutating the scorecard document as needed.

## No Gos

_Describe any features or behaviors that have been considered and rejected as out of scope for this project._

## Rabbit Holes

_Describe any solutions to problems that pose a risk to completing this project on time._

**Comment by randytpierce** [comment]
This is finished

**Comment by ian-noaa** [comment]
Was there an associated PR with these changes? I wasn't seeing any related commits on `development` and want to make sure we didn't lose commits in the shuffle.
