### ISSUE TITLE
cb_ceiling - comes up with older date range

### ISSUE THREAD

**Issue by gopa-noaa** [NOAA-GSL/MATS#943]
cb_ceiling app is coming up with older date range: 11/12/2022 17:00 - 12/12/2022 17:00
Could be due to metadata not getting refreshed.

**Comment by randytpierce** [comment]
Is this fixed now? I think Gopa and I fixed this. Need to verify in issue meeting.

**Comment by gopa-noaa** [comment]
Randy, what I remember is we did figure out if we run the metadata update SQLs into smaller parts, it works fine. I think you were planning to change the python-script/cron to enable that.

**Comment by bonnystrong** [comment]
Consider adding Molly to work on this after TC issues resolved.

**Comment by bonnystrong** [comment]
Blocked until someone has time available to work on this.

**Comment by bonnystrong** [comment]
Still have broken metadata.

**Comment by bonnystrong** [comment]
Needs completed for CB METAR app.  Changed to high priority

**Comment by mollybsmith-noaa** [comment]
Reassigning this to Gopa because he is working on the metadata now.

**Comment by bonnystrong** [comment]
What is the current status of this issue?

**Comment by mollybsmith-noaa** [comment]
This isn’t a MATS issue anymore as the metadata is working, it’s an ingest
issue as I don’t think the ingest has reliably run for a few months, so the
metadata is only picking up older dates.

**Comment by mollybsmith-noaa** [comment]
Fixed with the new metadata implementation
