### ISSUE TITLE
scorecard for "1 Hour Precipitation" RP_OPS HRRR_OPS produces wrong query 

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/MATS#946]
If the scorecard is given parameters like this.... 

![Screen Shot 2023-04-24 at 12 00 53 PM](https://user-images.githubusercontent.com/25647166/234082727-9474337f-0818-4674-a077-d022037f1fd5.png)

The query statements end up like this ```
SELECT m0.time AS avtime,
    SUM(m0.yy) AS hit,
    SUM(m0.yn) AS fa,
    SUM(m0.ny) AS miss,
    SUM(m0.nn) AS cn
FROM precip_new.HRRR_OPS_20km_StageIV_EUS AS m0
WHERE 1 = 1
    AND m0.time >= { { fromSecs } }
    AND m0.time <= { { toSecs } }
    AND floor((m0.time) %(24 * 3600) / 3600) IN(
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23
    )
    AND m0.trsh = 1
    AND m0.fcst_len = 1
GROUP BY avtime
ORDER BY avtime; ```

And that query statement doesn't work because the table that it is querying doesn't have those fields. That table is described like ```
"Field",   "Type","Null","Key","Default","Extra"
"time",     "int(10) unsigned","NO","PRI","",""
"fcst_len","tinyint(4)","NO","PRI","",""
"trsh",      "decimal(3,2)","NO","PRI","",""
"hit",         "mediumint(8) unsigned","NO","","",""
"miss",      "mediumint(8) unsigned","NO","","",""
"fa",           "mediumint(8) unsigned","NO","","",""
"cn",           "mediumint(8) unsigned","NO","","",""
```
so there are no yy, yn, ny, and nn fields.

**Comment by mollybsmith-noaa** [comment]
Usually our legacy contingency table databases use yy for hits, yn for false alarms, ny for misses, and nn for correct nulls, but this is a good reminder that radar and precipAccum use ny for false alarms and yn for misses (for some reason), while precipitation1hr just has the words hit, miss, fa, and cn. I'm currently updating the templates to reflect this.

**Comment by mollybsmith-noaa** [comment]
I fixed all of this on Friday.
