### ISSUE TITLE
Trailing slashes in app URL's breaks the link to the home page

### ISSUE THREAD

**Issue by ian-noaa** [NOAA-GSL/MATS#952]
## Describe the bug
Including a trailing `/` when visiting an app breaks the links back to the MATS home page. 

## To Reproduce

1. Go to https://esrl.noaa.gov/gsd/mats/anomalycor (or any other app on any other MATS server)
2. Click on "Home" or "Model Analysis Tool Suite (MATS)"
3. See that you're redirected to the homepage as expected
4. Go to https://esrl.noaa.gov/gsd/mats/anomalycor/ (note the trailing slash)
5. Click on "Home" or "Model Analysis Tool Suite (MATS)"
6. See that you're redirected to the app itself and not to the homepage as expected

## Expected behavior
We should be redirected to the home page regardless of if there's a trailing slash in the URL

**Comment by mollybsmith-noaa** [comment]
Ugh, this is because of more relative links in MATS. I thought I had rooted all of these out. Thanks for catching this one!

**Comment by mollybsmith-noaa** [comment]
It is replaced with an absolute path like it should have been before!
