### ISSUE TITLE
MATS app headers have old URLs

### ISSUE THREAD

**Issue by ian-noaa** [NOAA-GSL/MATS#953]
## Describe the bug
The headers in the MATS apps point to old GSD websites. 

## To Reproduce
1. Go to https://esrl.noaa.gov/gsd/mats/upperair
2. Click on "GSL Modeling" in the header
3. Land on the homepage for the old modeling development branch: esrl.noaa.gov/gsd/mdb
4. Click on "Global Systems Laboratory" in the header
5. Land on the lab's old homepage: esrl.noaa.gov/gsd before being redirected to the new gsl.noaa.gov

## Expected behavior
Users should be linked to an ASCEND webpage (or https://gsl.noaa.gov/research/research-divisions) and the new GSL website, (gsl.noaa.gov) respectively.

**Comment by mollybsmith-noaa** [comment]
I've updated all of the static and template header and footer links to be up to date and unbroken.
