### ISSUE TITLE
Create new Ensemble app

### ISSUE THREAD

**Issue by mollybsmith-noaa** [NOAA-GSL/MATS#961]
Jeff is nearly done with his new ensemble ingest, at which point we will add a new MATS app that can visualize the data.

**Comment by JeffHamiltonNOAA** [comment]
The new workflow is done and stats are being loaded into the new SQL ensemble database for reflectivity and precip. Now we will work together to ensure that plots are being generated that match Trevor's plotting script, which for reference is located in the following directory on Jet:

/whome/Trevor.Alcott/verify/plot_stats.py

**Comment by mollybsmith-noaa** [comment]
Status update: I'm currently in the process of writing and testing the necessary metadata scripts for this app (one for each database). The app framework exists as of last Thursday.

**Comment by bonnystrong** [comment]
Jeff needs to send Molly ENglish version of base rate calculations.  Needed for reliability plots.

**Comment by mollybsmith-noaa** [comment]
Just reliability plots left to finish

**Comment by mollybsmith-noaa** [comment]
Barring any changes that Jeff suggests, this app is done.
