### ISSUE TITLE
add tooltip to scorecard

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/MATS#965]
add tooltip to scorecard to show residual stat values.

**Comment by mollybsmith-noaa** [comment]
Tooltip should have p-value, mean, stdev, N.

**Comment by randytpierce** [comment]
moved to in progress because I have a little time waiting for a PR to merge

**Comment by randytpierce** [comment]
This is being worked on an "as time is available" basis. The plan is to have the data processor fill in a structure for a value instead of an integer value. The scorecard app needs to be modified so that it recognizes if a scorecard value is an integer or a structure. If it is a structure then the tooltip will fill in the data from the structure. If it is an integer it will provide a placeholder tooltip of some sort. Not a lot of work.

**Comment by randytpierce** [comment]
This is finished except that I need to have Molly merge it or wait for her to finish merging Gopa's work. Closing the issue because it is is complete, tested and just waiting for a merge to complete the PR.
