### ISSUE TITLE
cb_ceiling app, middleware implementation for PerformanceDiagram plots

### ISSUE THREAD

**Issue by gopa-noaa** [NOAA-GSL/MATS#969]
Evaluate to see if any significant performance improvements to be had using middl-tier approach, and if so implement SQL templates and MATScommon->matsMiddle classes for the same.

**Comment by mollybsmith-noaa** [comment]
Just so you know, this issue is not necessary, we don't use station plots for performance diagrams.

**Comment by gopa-noaa** [comment]
Closing issue per Molly's comment
